// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr9T86uGF1dQIKTvP37n-o59j1jarhu64',
    appId: '1:894359482269:web:e55124b597906a1a8f4974',
    messagingSenderId: '894359482269',
    projectId: 'givesync-74ea5',
    authDomain: 'givesync-74ea5.firebaseapp.com',
    storageBucket: 'givesync-74ea5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmGYrcFwZc9ABGIxVtazyMolgbaalOlb0',
    appId: '1:894359482269:android:5e976a75e28f7cbb8f4974',
    messagingSenderId: '894359482269',
    projectId: 'givesync-74ea5',
    storageBucket: 'givesync-74ea5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjtRVEzp0eBeK_azYEgzvXU719m2Y4ZjU',
    appId: '1:894359482269:ios:768b5d5de29038978f4974',
    messagingSenderId: '894359482269',
    projectId: 'givesync-74ea5',
    storageBucket: 'givesync-74ea5.firebasestorage.app',
    iosBundleId: 'com.example.givesyncApplication385',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjtRVEzp0eBeK_azYEgzvXU719m2Y4ZjU',
    appId: '1:894359482269:ios:768b5d5de29038978f4974',
    messagingSenderId: '894359482269',
    projectId: 'givesync-74ea5',
    storageBucket: 'givesync-74ea5.firebasestorage.app',
    iosBundleId: 'com.example.givesyncApplication385',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr9T86uGF1dQIKTvP37n-o59j1jarhu64',
    appId: '1:894359482269:web:d8ff7a1673c6aca58f4974',
    messagingSenderId: '894359482269',
    projectId: 'givesync-74ea5',
    authDomain: 'givesync-74ea5.firebaseapp.com',
    storageBucket: 'givesync-74ea5.firebasestorage.app',
  );
}
